---

- name: Add googlechrome rpm key
  ansible.builtin.rpm_key:
    key: "{{ googlechrome_rpm_key_url }}"

- name: Add google chrome repo
  ansible.builtin.yum_repository:
    description: google-chrome
    baseurl: "{{ googlechrome_yum_repository_url }}"
    gpgcheck: true
    skip_if_unavailable: true
    gpgkey: "{{ googlechrome_rpm_key_url }}"
    file: google-chrome
    name: google-chrome

- name: Install latest google chrome
  ansible.builtin.dnf:
    name: "{{ googlechrome_packages }}"

...
