---

virtualization_docker:
  packages:
    - moby-engine
    - docker-cli
    - containerd
    - docker-buildx
    - docker-compose
  user_groups:
    - docker

virtualization_kvm_qemu:
  package_groups:
    - '@Virtualization'
  packages:
    - virt-manager
    - edk2-ovmf
    - swtpm
    - quickemu
    - python3-libvirt
  systemd_services:
    - libvirtd
  user_groups:
    - libvirt
    - kvm
  networks:
    - default
    - isolated

virtualization_virt_manager_preferences:
  groups:
    - name: "Console Settings"
      base_path: "/org/virt-manager/virt-manager/console"
      items:
        - { key: "auto-redirect", value: "false" }
        - { key: "scaling", value: "0" }
        - { key: "resize-guest", value: "0" }
    - name: "General Settings"
      base_path: "/org/virt-manager/virt-manager"
      items:
        - { key: "xmleditor-enabled", value: "false" }

...
