---

virtualization_docker:
  packages:
    - moby-engine
    - docker-cli
    - containerd
    - docker-buildx
    - docker-compose
  user_groups:
    - docker

virtualization_kvm_qemu:
  package_groups:
    - '@Virtualization'
  packages:
    - virt-manager
    - edk2-ovmf
    - swtpm
    - quickemu
    - python3-libvirt
  systemd_services:
    - libvirtd
  user_groups:
    - libvirt
    - kvm
  networks:
    - default
    - isolated
...
