---

- name: Remove redundant packages often starting unnecessary services
  ansible.builtin.dnf:
    name: "{{ harden_system_redundant_packages }}"
    state: absent

- name: Turn off Link-Local Multicast Name Resolution (LLMNR)
  block:
    - name: Create directory /etc/systemd/resolved.conf.d
      ansible.builtin.file:
        path: /etc/systemd/resolved.conf.d
        state: directory
        owner: root
        group: root
        mode: '0755'


    - name: Create custom options file
      ansible.builtin.copy:
        owner: root
        group: root
        mode: '0644'
        dest: /etc/systemd/resolved.conf.d/options.conf
        content: |
          [Resolve]
          LLMNR=no
      notify:
        - Restart systemd-resolved
      changed_when: true

- name: Configure hardened Firewalld zone
  block:
    - name: Ensure 'FedoraWsHardened' zone exists with DROP target
      ansible.posix.firewalld:
        zone: FedoraWsHardened
        target: DROP
        state: present
        permanent: true
        immediate: true

    - name: Set 'FedoraWsHardened' as the default zone
      ansible.builtin.command: firewall-cmd --set-default-zone=FedoraWsHardened
      register: harden_system_set_default_zone
      changed_when: "'ZONE_ALREADY_SET' not in harden_system_set_default_zone.stderr"
