---

- name: Install Neovim packages
  ansible.builtin.dnf:
    name: "{{ neovim_dnf_packages }}"
    state: present

- name: Clone LazyVim starter repository
  become: true
  become_user: "{{ local_username }}"
  block:
    - name: Clone LazyVim starter git repo
      ansible.builtin.git:
        repo: "{{ neovim_lazyvim_starter_url }}"
        dest: "/home/{{ local_username }}/.config/nvim"
        version: main
