---

- name: Install Neovim packages
  ansible.builtin.dnf:
    name: "{{ neovim_dnf_packages }}"
    state: present


- block:
    - name: Clone LazyVim starter git repo
      ansible.builtin.git:
        repo: "{{ neovim_lazyvim_starter_url }}"
        dest: "~{{ ansible_user_id }}/.config/nvim"
  become: true
  become_user: "{{ ansible_user_id }}"

...
